# Generated by Django 3.1.4 on 2021-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMedix_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
