# Generated by Django 3.1.4 on 2021-10-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMedix_App', '0002_auto_20210924_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingappointment',
            name='Paymentstatus',
            field=models.BooleanField(default=False),
        ),
    ]
