# Generated by Django 3.1.4 on 2021-08-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMedix_App', '0002_auto_20210801_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='doctors',
            field=models.ManyToManyField(to='EMedix_App.doctor'),
        ),
    ]
