# Generated by Django 3.1.4 on 2021-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMedix_App', '0003_bookingappointment_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_records',
            name='recordname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
