# Generated by Django 3.1.4 on 2021-10-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMedix_App', '0004_medical_records_recordname'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_records',
            name='fileid',
            field=models.IntegerField(default=0),
        ),
    ]
